require('core.options')
require('core.keymaps')

-- requirplugins
require('plugins.plugins-setup')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.flash')
require('plugins.cmp')
require('plugins.comment')
require('plugins.fidget')
require('plugins.bufferline')
require('plugins.autopairs')
require('plugins.catppuccin')
require('plugins.telescope')
require('plugins.dashboard')
require('plugins.acc')
require('plugins.code_runner')
